apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: netflix
build:
  artifacts:
    - image: shokohsc-team/netflix
      context: .
      sync:
        manual:
          - src: ./internal/**/*.go
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s/base
deploy:
  kubectl: {}
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: shokohsc-team/netflix
          sync:
            manual:
              - src: ./internal/**/*.go
                dest: .
          docker:
            dockerfile: Dockerfile.dev
  - name: shokohsc
    build:
      artifacts:
        - image: shokohsc-team/netflix
          sync:
            manual:
              - src: ./internal/**/*.go
                dest: .
          kaniko:
            cache:
              repo: shokohsc-team/netflix
            dockerfile: Dockerfile.dev
      cluster:
        dockerConfig:
          secretName: kaniko-secret
        namespace: kaniko
        pullSecretName: kaniko-secret
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
    manifests:
      kustomize:
        paths:
          - k8s/overlays/shokohsc
    deploy:
      kubectl: {}
  - name: prod
    build:
      artifacts:
        - image: shokohsc-team/netflix
          kaniko:
            cache:
              repo: shokohsc-team/netflix
            dockerfile: Dockerfile
      cluster:
        dockerConfig:
          secretName: kaniko-secret
        namespace: kaniko
        pullSecretName: kaniko-secret
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi