---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_USERNAME
              value: netflix
            - name: POSTGRESQL_PASSWORD
              value: netflix
            - name: POSTGRESQL_DATABASE
              value: netflix
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: postgres
          livenessProbe:
            tcpSocket:
              port: postgres
          readinessProbe:
            tcpSocket:
              port: postgres
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 1000m
              memory: 512M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app.kubernetes.io/name: adminer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: adminer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adminer
    spec:
      automountServiceAccountToken: false
      containers:
        - name: adminer
          image: adminer:4.8.1-standalone
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ADMINER_PLUGINS
              value:
            - name: ADMINER_DESIGN
              value: dracula
            - name: ADMINER_DEFAULT_SERVER
              value: postgres
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 64M
            requests:
              cpu: 10m
              memory: 64M
