---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer
  annotations:
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    dashboard.shokohsc.home/icon: wrench
    dashboard.shokohsc.home/name: adminer
    dashboard.shokohsc.home/url: https://adminer.netflix.shokohsc.home
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "adminer.netflix.shokohsc.home"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: adminer
                port:
                  number: 80
  tls:
    - hosts:
        - "adminer.netflix.shokohsc.home"
      secretName: adminer-cert